import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import EmotionProvider from "./(providers)/EmotionProvider";

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
  display: "swap",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
  display: "swap",
});

export const metadata = {
  title: "Karyakart-Next",
  description: "Generated by Create Next App for Karyakart",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="min-h-screen bg-white text-black antialiased">
        <EmotionProvider>
          {children}
        </EmotionProvider>
      </body>
    </html>
  );
}
